# Generated by Django 2.1.3 on 2018-11-26 20:16

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Started Application'), (1, 'Completed Application'), (2, 'Reviewed Application'), (3, 'Tour Scheduled'), (4, 'Tour Completed'), (5, 'Tour Follow-Up'), (6, 'Prepared Contract'), (7, 'Sent Contract'), (8, 'Contract Returned'), (90, 'Email Communication'), (91, 'Phone Call'), (92, 'Physical Mailing'), (99, 'Other')], default=99, verbose_name='Type of Action')),
                ('date', models.DateTimeField(verbose_name='Date/Time')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False, verbose_name='Completed?')),
                ('applying_for', models.IntegerField(choices=[(-4, 'One-year-olds'), (-3, 'Two-year-olds'), (-2, 'Pre-K 3'), (-1, 'Pre-K'), (0, 'Kindergarten'), (1, '1st Grade'), (2, '2nd Grade'), (3, '3rd Grade'), (4, '4th Grade'), (5, '5th Grade'), (6, '6th Grade'), (7, '7th Grade'), (8, '8th Grade')], null=True, verbose_name='Grade level applying for')),
                ('current_grade', models.IntegerField(choices=[(-4, 'One-year-olds'), (-3, 'Two-year-olds'), (-2, 'Pre-K 3'), (-1, 'Pre-K'), (0, 'Kindergarten'), (1, '1st Grade'), (2, '2nd Grade'), (3, '3rd Grade'), (4, '4th Grade'), (5, '5th Grade'), (6, '6th Grade'), (7, '7th Grade'), (8, '8th Grade'), (-999, 'No school')], null=True, verbose_name='Current grade level')),
                ('schedule_time', models.IntegerField(choices=[(8, 'Full Days (7:30-3:30'), (5, 'Half Days (7:30-12:30'), (0, 'Other')], default=0, verbose_name='Schedule preference (Times)')),
                ('schedule_days', models.IntegerField(choices=[(5, '5 Days (Monday-Friday)'), (3, '3 Days (Monday, Wednesday, Friday)'), (2, '2 Days (Tuesday, Thursday)'), (0, 'Other')], default=0, verbose_name='Schedule preference (Days)')),
                ('schedule_more', models.CharField(blank=True, max_length=254, verbose_name='Scheduling notes')),
                ('student_age_months', models.IntegerField(default=0, verbose_name='Age in Months (School Year Start)')),
                ('student_age_years', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Age in Years (School Year Start)')),
                ('actions', models.ManyToManyField(blank=True, to='applyonline.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'Accomplishment'), ('R', 'Repeated Grade'), ('P', 'Psychological Evaluation'), ('E', 'Educational Evaluation'), ('S', 'Speech/Language Evaluation'), ('O', 'Occupational Therapy'), ('C', 'Professional Counseling'), ('X', 'Other')], default='X', max_length=2, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date of Birth')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Describe your child')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='First Name')),
                ('connections', models.BooleanField(default=False, verbose_name='Connections to school?')),
                ('connections_more', models.TextField(blank=True, verbose_name='More info')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Home Phone')),
                ('address', address.models.AddressField(null=-1, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('preferred_name', models.CharField(blank=True, max_length=50, verbose_name='Preferred Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('relationship', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('SF', 'Step-Father'), ('SM', 'Step-Mother'), ('GM', 'Grandmother'), ('GF', 'Grandfather'), ('U', 'Uncle'), ('A', 'Aunt'), ('LG', 'Legal Guardian'), ('S', 'Sibling')], default='LG', max_length=2, verbose_name='Relationship')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Mobile Phone')),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Work Phone')),
                ('hometown', models.CharField(blank=True, max_length=50, verbose_name='Hometown')),
                ('employer', models.CharField(blank=True, max_length=50, verbose_name='Employer')),
                ('job_title', models.CharField(blank=True, max_length=50, verbose_name='Job Title')),
                ('email', models.EmailField(max_length=254)),
                ('schools_attended', models.ManyToManyField(blank=True, to='applyonline.OtherSchool')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
                ('open', models.BooleanField(default=False, verbose_name='Open for Applications?')),
            ],
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applyonline.OtherSchool')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('preferred_name', models.CharField(max_length=50, verbose_name='Preferred Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer to not answer')], default='X', max_length=1, verbose_name='Gender')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Describe your child')),
                ('current_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_current', to='applyonline.OtherSchool')),
                ('evaluations', models.ManyToManyField(blank=True, to='applyonline.Evaluation')),
                ('schools_attended', models.ManyToManyField(blank=True, related_name='students_attended', to='applyonline.OtherSchool')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(blank=True, to='applyonline.Parent'),
        ),
        migrations.AddField(
            model_name='family',
            name='students',
            field=models.ManyToManyField(blank=True, to='applyonline.Student'),
        ),
        migrations.AddField(
            model_name='application',
            name='families',
            field=models.ManyToManyField(to='applyonline.Family'),
        ),
        migrations.AddField(
            model_name='application',
            name='other_schools',
            field=models.ManyToManyField(blank=True, to='applyonline.OtherSchool'),
        ),
        migrations.AddField(
            model_name='application',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applyonline.SchoolYear'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applyonline.Student'),
        ),
    ]
