# Generated by Django 2.1.3 on 2018-11-21 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('complete', models.BooleanField(default=False, verbose_name='Completed?')),
                ('student_age_months', models.IntegerField(default=0, verbose_name='Age in Months (School Year Start)')),
                ('student_age_years', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Age in Years (School Year Start)')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='First Name')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('preferred_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferred Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('relationship', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('SF', 'Step-Father'), ('SM', 'Step-Mother'), ('GM', 'Grandmother'), ('GF', 'Grandfather'), ('U', 'Uncle'), ('A', 'Aunt'), ('LG', 'Legal Guardian'), ('S', 'Sibling')], default='LG', max_length=2, verbose_name='Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
                ('open', models.BooleanField(default=False, verbose_name='Open for Applications?')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('preferred_name', models.CharField(max_length=50, verbose_name='Preferred Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(to='applyonline.Parent'),
        ),
        migrations.AddField(
            model_name='family',
            name='students',
            field=models.ManyToManyField(to='applyonline.Student'),
        ),
        migrations.AddField(
            model_name='application',
            name='families',
            field=models.ManyToManyField(to='applyonline.Family'),
        ),
        migrations.AddField(
            model_name='application',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applyonline.SchoolYear'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applyonline.Student'),
        ),
    ]
